<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5Q39FUQ" name="tests.FlowMapper" tests="28" failures="0" timestamp="4 Sep 2019 12:56:34 GMT" time="540.175" errors="2">
  <testcase name="flowMapperTest" time="14.472" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="14.992" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="22.200" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="17.999" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="18.739" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="34.332" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="18.534" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="18.869" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="39.050" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="17.717" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="18.123" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="21.705" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="2.194" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="31.648" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="23.504" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="17.372" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="42.468" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="20.030" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="19.058" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="17.450" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="22.225" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="11.461" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="14.215" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="14.505" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="16.096" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="6.433" classname="tests.FlowMapper">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at in.novopay.platform_ui.pages.web.SettlementPage.settlement(SettlementPage.java:416)
	at tests.ui.SettlementTest.settlementTest(SettlementTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at tests.FlowMapper.flowMapperTest(FlowMapper.java:103)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- flowMapperTest -->
  <testcase name="flowMapperTest" time="7.402" classname="tests.FlowMapper">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at in.novopay.platform_ui.pages.web.SettlementPage.settlement(SettlementPage.java:416)
	at tests.ui.SettlementTest.settlementTest(SettlementTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at tests.FlowMapper.flowMapperTest(FlowMapper.java:103)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- flowMapperTest -->
  <testcase name="flowMapperTest" time="17.382" classname="tests.FlowMapper"/>
</testsuite> <!-- tests.FlowMapper -->
